## Record the Audio and Convert to Text

In [1]:
# pip install SpeechRecognition
# conda update --force conda
# conda install pyaudio

In [8]:
import speech_recognition as sr

In [9]:
r = sr.Recognizer()

In [12]:
with sr.Microphone() as source:
    print('Say Something...')
    audio = r.listen(source, timeout = 10)
    
    try:
        text = r.recognize_google(audio)
        print('You were saying:')
        print(text)
    except:
        print('Sorry. Please try again.')

Say Something...
You were saying:
tomorrow I will be going to school so if you want you can come with me


## Convert Audio in Text Data 

In [13]:
import speech_recognition as sr

In [14]:
import numpy as np

In [15]:
from scipy.io import wavfile

In [17]:
fs, data = wavfile.read('data/laxmikant.wav')

C:\Users\ertug\anaconda3\lib\site-packages\ipykernel_launcher.py:1: WavFileWarning: Chunk (non-data) not understood, skipping it.
  """Entry point for launching an IPython kernel.


In [18]:
fs

44100

In [19]:
data

array([[-9.1552734e-05, -9.1552734e-05],
       [-6.1035156e-05, -6.1035156e-05],
       [-6.1035156e-05, -9.1552734e-05],
       ...,
       [-1.2207031e-04, -1.8310547e-04],
       [-1.2207031e-04, -9.1552734e-05],
       [-6.1035156e-05, -9.1552734e-05]], dtype=float32)

In [20]:
y = (np.iinfo(np.int32).max * (data/np.abs(data).max())).astype(np.int32)

In [21]:
np.iinfo(np.int32).max

2147483647

In [22]:
(data/np.abs(data).max())

array([[-0.00018557, -0.00018557],
       [-0.00012372, -0.00012372],
       [-0.00012372, -0.00018557],
       ...,
       [-0.00024743, -0.00037115],
       [-0.00024743, -0.00018557],
       [-0.00012372, -0.00018557]], dtype=float32)

In [23]:
y

array([[-398518, -398518],
       [-265679, -265679],
       [-265679, -398518],
       ...,
       [-531358, -797037],
       [-531358, -398518],
       [-265679, -398518]])

In [24]:
wavfile.write('data/laxmikant_int.wav', fs, y)

In [25]:
r = sr.Recognizer()

In [26]:
with sr.AudioFile('data/laxmikant_int.wav') as source:
    audio = r.listen(source)
    
    try:
        text = r.recognize_google(audio)
        print('Working on...')
        print(text)
    except:
        print('Sorry. Try again.')

Working on...
hello everyone how are you answer all of you are enjoying these listen and I would like to also request you to please leave your rating and if you have any doubts you can come into your questions in the question-and-answer section


##  Text to Audio

In [31]:
text = 'Seems like turkish text can not be pronounced well, so let\'s try english this time'

In [32]:
#!pip install gTTS

In [33]:
from gtts import gTTS as g

In [34]:
obj = g(text)
obj.save('data/english_gtts.mp3')